config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'repositories#index'

  resources :issues, only: %i[show]
  resources :repositories, only: %i[show index] do
    resources :issues, only: %i[index]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :issues, only: %i[show create]

      get 'repositories/:repository_id/issues' => 'issues#index'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
# frozen_string_literal: true

class Issue < ApplicationRecord
  store :metadata, accessors: %w[title state body], coder: JSON

  belongs_to :repository

  validates :action, :repository, presence: true

  delegate :name, to: :repository, prefix: true
  delegate :owner_name, to: :repository

  def as_json(options = nil)
    super({
      only: %w[id action repository_id created_at updated_at],
      methods: %w[repository_name owner_name]
    }.merge(options || {}))
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  store :metadata, accessors: %w[name full_name owner_name], coder: JSON

  has_many :issues, dependent: :destroy
end

app/controllers/api/v1/issues_controller.rb
module Api
  module V1
    class IssuesController < ApplicationController
      before_action :set_issue, only: %i[show]

      def index
        @issues = Issue.where(repository_id: params[:repository_id])

        render json: @issues
      end

      def show
        render json: @issue
      end

      def create
        return render(json: {}, status: :ok) if request.headers['X-GitHub-Event'].eql?('ping')

        @issue = IssueCreatorService.new(issue_attributes).build

        if @issue.save
          render json: @issue, status: :created
        else
          render json: @issue.errors.full_messages, status: :unprocessable_entity
        end
      end

      private

      def set_issue
        @issue = Issue.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render json: I18n.t('record_not_found'), status: :not_found
      end

      def issue_attributes
        params.permit(
          :action,
          issue: %i[id title state body],
          repository: [:id, :name, :full_name, owner: %i[id login]]
        )
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[show]

  def index
    @issues = Issue.where(repository_id: params[:repository_id])
  end

  def show; end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[show]

  def index
    @repositories = Repository.all
  end

  def show; end

  private

  def set_repository
    @repository = Repository.includes(:issues).find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZaittRorTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar is-white">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'ZaittRorTest', root_path, class: 'navbar-item brand-text' %>
          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Repositórios', repositories_path, class: 'navbar-item' %>
          </div>

        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <a class="badge" href="https://bulma.io">
      <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="128" height="24">
    </a>
  </body>
</html>

app/views/repositories/index.html.erb
<div class="column is-12">
  <div class="card">
    <div class="card-table">
      <div class="content">
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <%- @repositories.each do |repo|  %>
              <td><%= repo.id %></td>
              <td><%= link_to repo.name, repository_path(repo) %></td>
            <% end -%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/repositories/show.html.erb
<div class="column is-12">
  <div class="card">
    <div class="card-table">
      <div class="content">
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Full Name</th>
              <th>Owner Name</th>
            </tr>
          </thead>
          <tbody>
            <td><%= @repository.id %></td>
            <td><%= @repository.name %></td>
            <td><%= @repository.full_name %></td>
            <td><%= @repository.owner_name %></td>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%- @repository.issues.each do |issue| %>
  <div class="column is-12">
    <div class="card">
      <div class="card-table">
        <div class="content">
          <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
            <thead>
              <tr>
                <th>Id</th>
                <th>Title</th>
                <th>State</th>
                <th>Body</th>
              </tr>
            </thead>
            <tbody>
              <td><%= issue.id %></td>
              <td><%= issue.title %></td>
              <td><%= issue.state %></td>
              <td><%= issue.body %></td>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end -%>